### ISSUE TITLE
Does not work with external monitor unless useMouseMoveEvent variable is set to true on like 719

### ISSUE THREAD

**Issue by daintym0sh** [DarthBrento/MouseKeysPlusPlus#1]
For some reason, the useMouseMoveEvent variable must be true so the "move a pix move a mickey" logic runs. Is there a drawback to running this logic every time the moveMouse method is called?

**Comment by DarthBrento** [comment]
It lacks precision, the cursor won't move as smooth, but as far as I know, that's it. The option is there to be used if it does not work else. So use it if you need it.

**Comment by daintym0sh** [comment]
I have been using it all day with no issues. Thanks for putting this together. It is very helpful. Works much better than stock Windows mouse keys. Thanks!
